### PR TITLE
Link Release To Project feature

### PR DESCRIPTION
**Pull request by hoangnt2**
### Link Release To Project feature

image

This PR do:
- Add Link Release To Project modal to release detail page (Button Link To Project)
- Add Link Release To Project  modal to component detail page (Link icon)

### CODE REVIEW

**Review by heliocastro — APPROVED** [review]
LGTM

**Review by heliocastro — APPROVED** [review]
LGTM

**Comment by heliocastro** [comment]
@hoangnt2 You need resolve the conflicts

**Comment by hoangnt2** [comment]
> @hoangnt2 You need resolve the conflicts

Solved

**Review by heliocastro — APPROVED** [review]
LGTM

**Pull request merged**
