### PR TITLE
Check session

### PR DESCRIPTION
**Pull request by deo002**

### CODE REVIEW

**Comment by deo002** [comment]
I'll add too other pages as well once this is approved

**Comment by hoangnt2** [comment]
@deo002  I'm wondering where we can put it. It is a component but HOC is quite different in meaning.

**Comment by deo002** [comment]
> @deo002 I'm wondering where we can put it. It is a component but HOC is quite different in meaning.

Hmm...how about a folder named HOCs inside of components/sw360 and import it like this: import 'withAuth' from '@/components/sw360/HOCs'.

Also, I was considering renaming withAuth to loadSession.

What do you think?

**Comment by hoangnt2** [comment]
@deo002 I think **hocs** should be on same level with the **components** folder.

image

Here is example from ChatGPT

and **withAuth** should be kept (I had taken a look on some HOC example and they use that name format **with + sth**)

**Comment by heliocastro** [comment]
I'm still not 100% convinced though.
Is higher order component the correct solution and / or the only ?

**Comment by hoangnt2** [comment]
@heliocastro

The routes are protected by middleware.ts (as we configured in the project).

The problem with useSession is when you use useSession it will fetch the session from api/auth/session and it will take some time to wait so we need a piece of code to check if the session is fetched or not. I'm using HOC to reduce code duplication (check session code), not to protect routes.

**Comment by deo002** [comment]
@heliocastro The hoc is not for protecting routes, it's sole purpose is to wait(show spinner) until the session info is loaded and then provide it to the components that use it. 

If we use session before it has loaded, we get this error because session.user.token is undefined until then: 
Screenshot from 2023-11-06 11-13-05

We can discuss alternative approaches or how to improve this approach this week.

**Comment by deo002** [comment]
> @deo002 I think **hocs** should be on same level with the **components** folder.
> 
> image
> 
> Here is example from ChatGPT
> 
> and **withAuth** should be kept (I had taken a look on some HOC example and they use that name format **with + sth**)
> 
> @heliocastro could you give me and @deo002 some advices?

Sounds good!

**Comment by heliocastro** [comment]
> 
> We can discuss alternative approaches or how to improve this approach this week.

useSession has a intermediate state ( loading ), to do exactly the timing difference. We do need discuss this one, before we overcomplicate all.

**Comment by deo002** [comment]
> > We can discuss alternative approaches or how to improve this approach this week.
> 
> useSession has a intermediate state ( loading ), to do exactly the timing difference. We do need discuss this one, before we overcomplicate all.

Sure! Let's discuss.

**Comment by heliocastro** [comment]
Closing this one as we are already using better solution

**Pull request closed without merging**
