### PR TITLE
feat(project_attachments): Add view for project attachments

### PR DESCRIPTION
**Pull request by deo002**
Found this Issue for adding variable length rows in GridJS: https://github.com/grid-js/gridjs/issues/453. ShowAttachmentTextOnExpand function's implementation is based on one of the comments in this PR.

### CODE REVIEW

**Review by hoangnt2 — COMMENTED** [review]
Please add translation strings for other languages

**Comment by deo002** [comment]
> Please add translation strings for other languages

Which tool to use to translate? Is it ok if I add empty strings for translations in other languages(I remember Helio asking me not to do it)?

**Review by heliocastro — APPROVED** [review]
LGTM

**Comment by hoangnt2** [comment]
> > Please add translation strings for other languages
> 
> Which tool to use to translate? Is it ok if I add empty strings for translations in other languages(I remember Helio asking me not to do it)?

You can use i18n-ally to do that. Install it as a extension in vscode

**Pull request merged**
