### PR TITLE
feat(Cypress): Add cypress e2e testing for components/releases page

### PR DESCRIPTION
**Pull request by maipt1**
- Add test scripts for components and releases.
- Test scenarios according to **https://eclipse.dev/sw360/docs/development/testcases/**

## Pre-condition:
New front-end commit id:  **6c8bb397adefa84703557fd11507a660c59b8ba7**
### 1. Requirement software

- Nodejs
    ```sh
    $ sudo apt-get update
    $ curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
    $ sudo apt install nodejs -y
    // Check nodejs version
    $ nodejs -v
    ```
- NPM
    ```
    $ sudo apt-get install npm
    // Check npm version
    $ npm -v
    ```
- Google Chrome latest version

***Note***: Recommended environment is Ubuntu 22.04 LTS, Nodejs v20.5.0, NPM 10.2.5

### 2. Setup project

- Clone source code for testing
    ```sh
    $ git clone https://github.com/eclipse-sw360/sw360-frontend.git
    $ cd sw360-frontend
    ```
- Install dependencies
    ```sh
    $ sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    $ npm i
    $ sudo apt-get install jq
    ```
***Reference***: https://docs.cypress.io/guides/getting-started/installing-cypress#System-requirements

#### 3.1. Setup testing

- Change cypress configuration
    ```sh
    $ vim cypress.env.json
    ```

- Change these configs, keep others:
    - "sw360_base_url": ${sw360 frontend url}
    - "sw360_api_server": ${sw360 rest api url}
    - "couchdb_ip": ${couchdb url}
    - "couchdb_port": ${couchdb port}
    - "couchdb_username" ${couchdb username}
    - "couchdb_password" ${couchdb password}

#### 3.2. Prerequisite:

- There is an user in sw360 liferay with:
    - username: admin@sw360.org
    - password: 12345

#### 3.3. Run with Cypress UI

- Open Cypress 
    ```sh
    $ npm test
    ```
- Select a specify test file: <**file name**>.cy.js

#### 3.4. Run in headless mode

- Run all tests:
    ```sh
    $ npx cypress run --browser chrome
    ```

- Run a specify test:
    ```sh
    $ npx cypress run --browser chrome --spec <file.cy.js> <file1.cy.js> <file2.cy.js> ...
    ```

runDemoAutoTest

### CODE REVIEW

**Comment by maipt1** [comment]
We have implemented e2e testing for components and releases. Please take a look at it and if you have any questions, please let me know.
[SW360 New Frontend] Automation Test #212

**Comment by KoukiHama** [comment]
@heliocastro @ag4ums @amritkv @arunazhakesan 

Please feel free to comment for this PR!

**Comment by amritkv** [comment]
Hey @KoukiHama & @hoangnt2  !

It looks awesome to me, as of now ! 
And moreover the library Cypress looks lightweight compared to the existing solutions, specifically for our project.

Need to dig deeper to understand it's usages in complex scenarios like tables.

**Comment by hoangnt2** [comment]
@heliocastro @amritkv @deo002, we have completed the Cypress code for the components/releases page. Please review it and share your feedback

**Review by heliocastro — APPROVED** [review]
Ia a big step ahead
Thanks guys for this. 

I would appreciate a guide on how we should use it in our project, or pointing out good examples.

**Comment by hoangnt2** [comment]
> Ia a big step ahead Thanks guys for this.
> 
> I would appreciate a guide on how we should use it in our project, or pointing out good examples.

@heliocastro  We plan to integrate it into GitHub Actions. The test will be executed whenever someone creates a PR. This will ensure that the PR does not affect existing functionality.

**Pull request merged**
