### PR TITLE
refactor: Move to pnpm

### PR DESCRIPTION
**Pull request by heliocastro**
Move the main package manager to pnpm

### CODE REVIEW

**Comment by heliocastro** [comment]
@hoangnt2 The change for pnpm has an interesting side effect, is running cypress tests by default.

**Review by hoangnt2 — APPROVED** [review]
Look good to me

**Comment by hoangnt2** [comment]
@heliocastro Sorry, but what do you mean by 'is running Cypress tests by default'?

**Comment by heliocastro** [comment]
> @heliocastro we are using e2e testing strategy for cypress, so a running application is needed for testing. Running cypress while building application will cause it to error

No no, build check the cypress tests, if all is ready to run.

**Pull request merged**
