### PR TITLE
Projects/add project/linked releases and projects

### PR DESCRIPTION
**Pull request by amritkv**
This PR is just to replace the auth token with session token for add project pages.

### CODE REVIEW

**Review by heliocastro — APPROVED** [review]
Good to go

**Comment by heliocastro** [comment]
@amritkv Remember to run the build always before submit.
```npx run build``` do the trick

**Comment by amritkv** [comment]
> @amritkv Remember to run the build always before submit. `npx run build` do the trick

Yeah ! By mistake I pushed it before building.
Thanks @heliocastro  ! :+1:

**Review by heliocastro — APPROVED** [review]
LGTM

**Pull request merged**
