### PR TITLE
fix(auth): Oidc based authentication with backend

### LINKED ISSUE #313: OIDC auth. with backend rest authorization server

### PR DESCRIPTION
**Pull request by smrutis1**
* Added a new custom OIDC/Oauth2 provider for authorization/authentication with the backend 

Closes #313

### CODE REVIEW

**Comment by smrutis1** [comment]
Should be tested once this PR https://github.com/eclipse-sw360/sw360/pull/2559 is merged in the backend

**Comment by smrutis1** [comment]
My `.env` looks like below 
image

**Comment by amritkv** [comment]
Hi @smrutis1 !

I tried to test it, as per your descriptions. But I'm getting `ECONNREFUSED` here to 8080. Attaching screenshot of it.

image

**Review by heliocastro — APPROVED** [review]
LGTM

**Pull request merged**
