### PR TITLE
feat(project): Added external urls integration while creating project

### PR DESCRIPTION
**Pull request by amritkv**
Feature :  Added the integration of external urls while creating a project

### CODE REVIEW

**Comment by hoangnt2** [comment]
@amritkv I am unable to enter the Additional Data, External Ids, Additional Roles. Do you have this problem?

**Comment by amritkv** [comment]
> Additional Data, External Ids, Additional Roles

@hoangnt2 Yupp, in my case its working fine.

**Comment by amritkv** [comment]
> @amritkv I am unable to enter the Additional Data, External Ids, Additional Roles. Do you have this problem?

@hoangnt2 
And this PR is to add only External Urls only. I will add next PR including Addtional Data, External Ids and Additional Roles

**Review by hoangnt2 — APPROVED** [review]

**Comment by hoangnt2** [comment]
@amritkv, Code look good

Could you fix the tool tip in next PR?
image

**Pull request merged**
