### PR TITLE
feat(home-page): Added list of releases under my comp subscriptions

### PR DESCRIPTION
**Pull request by amritkv**
Added list of releases under my comp subscriptions along with list of components

### CODE REVIEW

**Comment by heliocastro** [comment]
To make it easy, there's one error only in the middle of the warnings:
```39:23  Error: Type string trivially inferred from a string literal, remove type annotation.  @typescript-eslint/no-inferrable-types```

**Review by heliocastro — CHANGES_REQUESTED** [review]
Please add both signon and gpg signon

❯ git-unsigned.sh                     
418bdb2ffe944c809f92573707024044fee7ae6d	Amrit Kumar Verma	feat(home-page): Added list of releases under my comp subscriptions	N

**Comment by heliocastro** [comment]
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by heliocastro** [comment]
@amritkv home ( and css ) are moved now to src/app/[locale]/home folder.
Please adjust your code to the new layout.

**Comment by amritkv** [comment]
As helio suggested a new template for all the pages, the existing code need to be moved to the new template.
So, I am closing this PR.

**Pull request closed without merging**
