### PR TITLE
Fix table bugs

### PR DESCRIPTION
**Pull request by hoangnt2**
- Fixed bug incorrect table props are updated when the table is re-rendered
- Fixed an issue where tables using server paging were re-rendered multiple times (Project, Component, Vulnerability pages)

### CODE REVIEW

**Comment by deo002** [comment]
Looks cool!

**Review by heliocastro — APPROVED** [review]
LGTM

**Comment by heliocastro** [comment]
@hoangnt2 Out of curiosity, i like the idea of remove some props logic from the constructor, but is there another reason you did that ? Reuse it in extend table ?

**Comment by hoangnt2** [comment]
> @hoangnt2 Out of curiosity, i like the idea of remove some props logic from the constructor, but is there another reason you did that ? Reuse it in extend table ?

@heliocastro, that logic is also used in **com ComponentDidUpdate** so I moved it out of the constructor to reuse it.

**Pull request merged**
