### PR TITLE
Add the resource using tables for release and component detail page

### PR DESCRIPTION
**Pull request by hoangnt2**
### Add the resource using tables for release and component detail page

image

### CODE REVIEW

**Review by heliocastro — DISMISSED** [review]
LGTM

**Comment by heliocastro** [comment]
@hoangnt2 You need to fix the conflicts

**Comment by hoangnt2** [comment]
> @hoangnt2 You need to fix the conflicts

@heliocastro I solved it

**Review by heliocastro — APPROVED** [review]
LGTM

**Comment by hoangnt2** [comment]
@heliocastro I have solved the conflict and add a new commit to show the counter for projects (this will work after [My PR](https://github.com/eclipse-sw360/sw360/pull/2107) is merged)
Screenshot from 2023-09-05 09-46-14

**Review by heliocastro — APPROVED** [review]
LGTM

**Pull request merged**
