### PR TITLE
Admin licenses1

### PR DESCRIPTION
**Pull request by deo002**

### CODE REVIEW

**Comment by deo002** [comment]
The translation files are being reformatted on comitting for some reason

**Review by heliocastro — CHANGES_REQUESTED** [review]
Please leave empty all other languages taht is not properly translated.
Adding english in the fields will make the automatic detector of missing transalation lost.
So, i do recommend leave all  the entries empty

**Comment by heliocastro** [comment]
> The translation files are being reformatted on comitting for some reason

If you setup husky properly in your system, yes, files are reformatted before be commit. Is intentional.

**Comment by deo002** [comment]
> Please leave empty all other languages taht is not properly translated. Adding english in the fields will make the automatic detector of missing transalation lost. So, i do recommend leave all the entries empty

Done

**Pull request merged**
