### PR TITLE
feat(App_Folder): Migrate to App folder (Auth page and Components page)

### PR DESCRIPTION
**Pull request by hoangnt2**
Refer PR: #24 

## Changes:
- Migrate from **/pages** to **/app** (auth and components page firstly)
- Replace **next-i18next** by **next-intl**
- Change environment variable from **SW360_API_URL** to **NEXT_PUBLIC_SW360_API_URL**
- Modify css

### CODE REVIEW

**Comment by heliocastro** [comment]
@hoangnt2 Please sign your email with a public gpg key, preferably yours.
❯ git-unsigned.sh 
4b25706310ac4131911d3fae5f3e4b0f98d457e7	hoangnt2	feat(App_Folder): Migrate to App folder (Auth page and component page)	E

**Review by heliocastro — CHANGES_REQUESTED** [review]
Add proper gpg signing

**Comment by heliocastro** [comment]
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by hoangnt2** [comment]
@heliocastro, I think that I had signed my commit
image

**Review by heliocastro — APPROVED** [review]
Approved.
Disregard the signature issue, i will ask to sysadmins take a look on the issue

**Pull request merged**
