### PR TITLE
feat(auth): Added username and password based basic authentication

### PR DESCRIPTION
**Pull request by smrutis1**
- Added a new credentials provider for basic authentication with backend.
- Ref Issue: #287

### CODE REVIEW

**Comment by smrutis1** [comment]
This is what my `.env` file look like
image

**Review by heliocastro — APPROVED** [review]
LGTM

**Comment by heliocastro** [comment]
@smrutis1 You didn't have a gpg signing. Read this carefully
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by heliocastro** [comment]
I cosigned and merged your branch, closing the PR.
@ag4ums Please verify in the future if all your devs are properly set with GPG keys and their git sign in environments

**Pull request closed without merging**
