### PR TITLE
Refactor requests pages

### PR DESCRIPTION
**Pull request by deo002**

### CODE REVIEW

**Comment by heliocastro** [comment]
@deo002 Why closing ?

**Comment by deo002** [comment]
> @deo002 Why closing ?

I noticed you had already done the required changes for removing linting errors after creating the PR.

**Comment by heliocastro** [comment]
@deo002 Please review it, because i moved the typing required from error to warning, meaning some of your changes may still make sense

**Comment by deo002** [comment]
> @deo002 Please review it, because i moved the typing required from error to warning, meaning some of your changes may still make sense

Ok, will do that

**Pull request closed without merging**
