### PR TITLE
feat(homepage): Enhanced home page. Added my subs(comp & releases), r…

### PR DESCRIPTION
**Pull request by amritkv**
Added My Subscriptions (components & releases), Recent components, and Recent releases in the new home page template.

Note : As per the discussions with helio, today we need to do some modifications in rest api (addition of `description` field in response root), the service files are deleted as of now. The description columns in the home page table are replaced by some other response data fields as of now.

### CODE REVIEW

**Review by heliocastro — APPROVED** [review]

**Comment by heliocastro** [comment]
@amritkv Please rebase your code and all is fine.
Just add back the "description" entry

**Review by heliocastro — DISMISSED** [review]

**Comment by hoangnt2** [comment]
image
@amritkv You can modify footer's style in global.css file

**Comment by amritkv** [comment]
> @amritkv Please rebase your code and all is fine. Just add back the "description" entry

Sure ! Will do that.

**Comment by amritkv** [comment]
> image @amritkv You can modify footer's style in global.css file

Sure ! Will do that.

**Comment by heliocastro** [comment]
> > image @amritkv You can modify footer's style in global.css file
> 
> Sure ! Will do that.

Or inside the component. @hoangnt2 Always better keep the css for the component inside the component, and only keep the global things .. errr .. global :-)

**Comment by hoangnt2** [comment]
> > > image @amritkv You can modify footer's style in global.css file
> > 
> > 
> > Sure ! Will do that.
> 
> Or inside the component. @hoangnt2 Always better keep the css for the component inside the component, and only keep the global things .. errr .. global :-)

Of course, but I defined it in global and we have only one footer so I think it's OK.

**Comment by amritkv** [comment]
> > > > image @amritkv You can modify footer's style in global.css file
> > > 
> > > 
> > > Sure ! Will do that.
> > 
> > 
> > Or inside the component. @hoangnt2 Always better keep the css for the component inside the component, and only keep the global things .. errr .. global :-)
> 
> Of course, but I defined it in global and we have only one footer so I think it's OK.

@heliocastro @hoangnt2 I have placed the footer css in global css file.

**Comment by amritkv** [comment]
> @amritkv Please rebase your code and all is fine. Just add back the "description" entry

@heliocastro I have incorporated the changes of description into services.

And just a small modification, I have renamed the `sw360fetchprojectdata.service.ts` file to `sw360fetchcompletedata.service.ts` to make it generic (usable for both my project & my components).

**Review by heliocastro — APPROVED** [review]
GTG

**Pull request merged**
